language: ruby

before_install:
  - gem update --system
  - gem install bundler

env:
  - "RAILS_VERSION=3.2.22"
  - "RAILS_VERSION=4.2.11"
  - "RAILS_VERSION=5.2.3"
  - "RAILS_VERSION=6.0.0.rc1"

rvm:
  - 2.3
  - 2.6
